### PR TITLE
Fix #303: Introduce flag --microceph-ip for cluster bootstrap

### LINKED ISSUE #303: Unable to set microcephd ip address
# Issue report
I cannot set microcephd listening ip when using `microceph cluster bootstrap`

## What version of MicroCeph are you using ?
microceph (reef/stable) 18.2.0+snap3f8909a69a

## What are the steps to reproduce this issue ?
```
microceph cluster bootstrap --mon-ip 10.165.2.8 --public-network 10.165.2.0/24 --cluster-network 10.165.2.0/24
```

## What happens (observed behaviour) ?
```
root@vm-1:~# ss -ltunp                                                             
Netid State  Recv-Q Send-Q     Local Address:Port  Peer Address:PortProcess                                                                                    
tcp   LISTEN 0      512           10.165.2.8:6800       0.0.0.0:*    users:(("ceph-mds",pid=1392829,fd=18))       
tcp   LISTEN 0      512           10.165.2.8:6801       0.0.0.0:*    users:(("ceph-mds",pid=1392829,fd=19))       
tcp   LISTEN 0      512           10.165.2.8:6802       0.0.0.0:*    users:(("ceph-mgr",pid=1392722,fd=27))       
tcp   LISTEN 0      512           10.165.2.8:6803       0.0.0.0:*    users:(("ceph-mgr",pid=1392722,fd=28))       
tcp   LISTEN 0      4096      <my-public-ip>:7443       0.0.0.0:*    users:(("microcephd",pid=1392402,fd=9))
tcp   LISTEN 0      512           10.165.2.8:3300       0.0.0.0:*    users:(("ceph-mon",pid=1392604,fd=27))       
tcp   LISTEN 0      512           10.165.2.8:6789       0.0.0.0:*    users:(("ceph-mon",pid=1392604,fd=28)) 
```
## What were you expecting to happen ?

```
root@vm-1:~# ss -ltunp                                                             
Netid State  Recv-Q Send-Q     Local Address:Port  Peer Address:PortProcess                                                                                    
tcp   LISTEN 0      512           10.165.2.8:6800       0.0.0.0:*    users:(("ceph-mds",pid=1392829,fd=18))       
tcp   LISTEN 0      512           10.165.2.8:6801       0.0.0.0:*    users:(("ceph-mds",pid=1392829,fd=19))       
tcp   LISTEN 0      512           10.165.2.8:6802       0.0.0.0:*    users:(("ceph-mgr",pid=1392722,fd=27))       
tcp   LISTEN 0      512           10.165.2.8:6803       0.0.0.0:*    users:(("ceph-mgr",pid=1392722,fd=28))       
tcp   LISTEN 0      4096          10.165.2.8:7443       0.0.0.0:*    users:(("microcephd",pid=1392402,fd=9))
tcp   LISTEN 0      512           10.165.2.8:3300       0.0.0.0:*    users:(("ceph-mon",pid=1392604,fd=27))       
tcp   LISTEN 0      512           10.165.2.8:6789       0.0.0.0:*    users:(("ceph-mon",pid=1392604,fd=28)) 
```

## Additional comments.

While looking at [the bootstrap code](https://github.com/canonical/microceph/blob/f10f54cd2d1d2e1d716715b1224d6eac9ed67963/microceph/cmd/microceph/cluster_bootstrap.go#L55-L71) it does not seem to be possible to overwrite the microcephd-IP.
It only seems to be possible with `microceph init` in the interactive setup (as [this code](https://github.com/canonical/microceph/blob/f10f54cd2d1d2e1d716715b1224d6eac9ed67963/microceph/cmd/microceph/init.go#L62-L67) shows) but there it is not possible to set the ceph ips...

### PR DESCRIPTION
**Pull request by krombel**
Fixes #303

### CODE REVIEW

**Comment by sabaini** [comment]
@krombel there's a bit of test flakiness i.e. false negatives here which seem unrelated to your change. However we would need a contributor licence and have the commit signed before we can merge I'm afraid. Cf. https://ubuntu.com/legal/contributors for details.

**Comment by sabaini** [comment]
Hey @krombel it looks like the CLA check still fails. From the log messages it says (redacted):

```
Checking the following users on Launchpad:
- <...>@<...>.de ✕ (has no Launchpad account)
```

**Comment by sabaini** [comment]
Hey @cgsamp thanks for that nice howto. However we would need a contributor licence and have the commit signed before we can merge I'm afraid. Cf. https://ubuntu.com/legal/contributors for details.

**Comment by krombel** [comment]
Can you rerun the CLA test? As of a few minutes ago I think it should be working now

**Comment by sabaini** [comment]
Thank you @krombel !

**Pull request merged**
