### PR TITLE
Add contrib guidelines

### PR DESCRIPTION
**Pull request by sabaini**

### CODE REVIEW

**Review by lmlg — COMMENTED** [review]
Looks great overall. The only thing I'd maybe add is a short paragraph about how to report Issues? As in, gather all relevant information, remember to specify version, upload logs if possible, etc. But it's a rather minor thing.

**Comment by sabaini** [comment]
Thanks @lmlg for the suggestion.
With Github issues repo owners can add templates for bug reporting, this probably would be preferable to guide users through creating bug reports. If you're ok with this I'll add a sep. card to create such a template

**Comment by lmlg** [comment]
> Thanks @lmlg for the suggestion. With Github issues repo owners can add templates for bug reporting, this probably would be preferable to guide users through creating bug reports. If you're ok with this I'll add a sep. card to create such a template

absolutely, that seems like the right approach.

**Review by lmlg — APPROVED** [review]

**Comment by sabaini** [comment]
Added CEPH-428

**Pull request merged**
