### PR TITLE
Created S3 test how-to

### PR DESCRIPTION
**Pull request by cgsamp**
Created a new how-to describing the process I used to test the Ceph S3 service using Microceph. I am not familiar with rst documentation but attempted to copy format from an example, and used markdown. I used a ubuntu server 22 virtual machine to deploy microceph, and used s3cmd on my local macbook. I have not tested installing and using s3cmd on Windows.

I am happy for the maintainers to edit in any way, and will respond to any suggestions or requests for revision.

Thank you!

### CODE REVIEW

**Comment by cgsamp** [comment]
I have tried to format the JSON user config appropriately, but I can't find the spec for the json linter and don't want to mess with your docs/.sphinx/requirements.txt. It seems to be guiding me to a flat one-indent-level format, which isn't how I prefer to format nested json.

**Comment by sabaini** [comment]
Hey @cgsamp thanks for that nice howto. However we would need a contributor licence and have the commit signed before we can merge I'm afraid. Cf. https://ubuntu.com/legal/contributors for details.

**Comment by UtkarshBhatthere** [comment]
@cgsamp the prompt says PR or contact `Please add the Canonical Project Manager or contact`.

**Comment by sabaini** [comment]
> Hi Peter, I did fill that out over the weekend, but didn't identify anyone as the "Canonical Project Manager." Should I complete it again and list you?

Hi @cgsamp , no I don't believe that's necessary. The test seems to be failing b/c it can't find the account you listed (c***@g***.com) on launchpad afaict

**Comment by cgsamp** [comment]
I completed the form again. I believe it is now correct.

**Comment by sabaini** [comment]
Hey @cgsamp , the CLA check succeeds now, nice!

We have 3 failing checks left over:

- unit test: this is an unrelated test env issue 
- Commits signed off: we'd need your commits to be signed please -- ideally squash the commits into one and sign that
- The spell checker tripped up a few times, I've pasted the results [here](https://paste.ubuntu.com/p/Z7wwqkGKB2/). There are a number of words the spellchecker doesn't recognize, these would need to be added to the wordlist in 
docs/.custom_wordlist.txt

cheers!

**Comment by cgsamp** [comment]
Closing this one and creating a simpler version.

**Pull request closed without merging**
