### PR TITLE
Make ceph.conf world-readable

### PR DESCRIPTION
**Pull request by sabaini**
For easier integration

### CODE REVIEW

**Review by tomponline — APPROVED** [review]
Thank you!

**Comment by tomponline** [comment]
@sabaini thanks for this. Which snap channel edge channel will it appear in first so we can test?

**Comment by sabaini** [comment]
@tomponline channel latest/edge now has the freshly built snap

**Comment by tomponline** [comment]
@sabaini many thanks, will test. Any ideas when that goes to the stable channel btw?

**Pull request merged**
